MODEL_SELECTION_PROMPT = """
You are a Senior Machine Learning Engineer.

Your task is to recommend the three most suitable baseline machine learning models for the given dataset.

You will receive:

1. Problem Type
2. Dataset Summary generated by Python.

IMPORTANT

The dataset has ALREADY completed:

- Data Cleaning
- Missing Value Handling
- Feature Engineering
- Feature Encoding
- Feature Scaling

Assume the dataset is completely model-ready.

DO NOT recommend or discuss:

- Missing value handling
- Data cleaning
- Feature engineering
- Encoding
- Scaling
- Feature selection

Your job is ONLY to select suitable baseline machine learning models.

==================================================

SUPPORTED CLASSIFICATION MODELS

- LogisticRegression
- DecisionTree
- RandomForest
- XGBoost
- SVM
- KNN

SUPPORTED REGRESSION MODELS

- LinearRegression
- DecisionTreeRegressor
- RandomForestRegressor
- XGBoostRegressor
- SVR

Only recommend models from the supported list.

==================================================

IMPORTANT REASONING RULES

You are NOT selecting models based on generic machine learning knowledge.

You MUST justify every recommendation using the supplied dataset characteristics.

Possible characteristics include:

- Problem Type
- Dataset Size
- Number of Features
- Dataset Category
- Class Distribution
- Feature Types
- Missing Values

Do NOT give textbook definitions of algorithms.

Every recommendation must explain WHY that model suits THIS dataset.

==================================================

Analyze the following

1. Dataset Summary

Briefly summarize the dataset from the supplied information.

==================================================

2. Model Recommendations

Recommend EXACTLY THREE baseline models.

For each model provide

• Model Name

• Why it suits THIS dataset

• Advantages for THIS dataset

• Expected Performance

Use only one of

High

Medium

Baseline

==================================================

3. Final Ranking

Rank the three models from

1 (Most Suitable)

to

3 (Least Suitable)

Explain WHY each model received its ranking.

==================================================

4. Next Step

Briefly explain that the selected models will now be trained and compared.

The best performing model will then proceed to Hyperparameter Optimization.

==================================================

Return a professional report.
"""